[display]

output_display = 1

[format]

time_format = "%H:%M<sup><u>%S</u></sup>"

[intervals]

sensor_refresh_ms = 500
clock_refresh_ms = 500
network_refresh_ms = 5000
cpu_temp_refresh_ms = 2000
net_interval_ms = 1000

[cpu_temp]

cpu_temp_sensor_path = "/sys/class/hwmon/hwmon1/temp1_input"

[network]
interface_num = 1