# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(400, 300)
        Weather.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(Weather)
        self.gridLayout.setObjectName("gridLayout")
        self.temperatureLabel = QtWidgets.QLabel(Weather)
        self.temperatureLabel.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.gridLayout.addWidget(self.temperatureLabel, 0, 1, 1, 1)
        self.humidityLabel = QtWidgets.QLabel(Weather)
        self.humidityLabel.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.humidityLabel.setFont(font)
        self.humidityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.humidityLabel.setObjectName("humidityLabel")
        self.gridLayout.addWidget(self.humidityLabel, 0, 2, 1, 1)
        self.pressureLabel = QtWidgets.QLabel(Weather)
        self.pressureLabel.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pressureLabel.setFont(font)
        self.pressureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureLabel.setObjectName("pressureLabel")
        self.gridLayout.addWidget(self.pressureLabel, 0, 3, 1, 1)
        self.we_condition = QtWidgets.QPushButton(Weather)
        self.we_condition.setMaximumSize(QtCore.QSize(100, 100))
        self.we_condition.setText("")
        icon = QtGui.QIcon.fromTheme("weather-clear")
        self.we_condition.setIcon(icon)
        self.we_condition.setIconSize(QtCore.QSize(96, 96))
        self.we_condition.setObjectName("we_condition")
        self.gridLayout.addWidget(self.we_condition, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "Form"))
        self.temperatureLabel.setText(_translate("Weather", "0"))
        self.humidityLabel.setText(_translate("Weather", "0"))
        self.pressureLabel.setText(_translate("Weather", "0"))
